#!/bin/bash
#for net in fc_1 fc_2 fc_3 fc_4 fc_5 fc_6 fc_7 conv_1 conv_2 conv_3 conv_4
# for net in conv_base conv_1 conv_2 conv_3 conv_4 
# do
# 	echo Evaluating network ${net}...
# 	for spec in `ls preliminary_evaluation_test_cases/${net}`
# 	do
# 		python code/verifier.py --net ${net} --spec preliminary_evaluation_test_cases/${net}/${spec}
# 	done
# done



# for net in  fc_6
# do
# 	echo Evaluating network ${net}...
# 	for spec in `ls test_cases/${net}`
# 	do
# 		python code/alpha_verifier.py --net ${net} --spec test_cases/${net}/${spec}
# 	done
# done


while IFS="" read -r p || [ -n "$p" ]
do
  # split the line into an array
  IFS=',' read -r -a array <<< "$p"
  # assign first element to net
  net=${array[0]}
  case=${array[1]}
  label=${array[2]}
  # only if net contains "conv" at beginning
  if [[ $net != conv* ]]; then
    continue
  fi
  echo ${net} ${case} ${label}
  python code/alpha_verifier.py --net ${net} --spec preliminary_evaluation_test_cases/${net}/${case}  
done < preliminary_evaluation_test_cases/gt.txt